<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    
    <meta name="viewport" content="width=device-width, maximum-scale=1.5" />
  
    <title><?php echo $viewData['title']; ?></title>

    <base href="<?php echo trim(Config::$SERVER, '/') . '/' . trim(Config::$SUBDIR, '/') . '/'; ?>" />
    
    <meta name="description" content="This is an example page rendered with the .P MVC framework." />
    <meta name="keywords" content="MVC, framework, .P, example" />
    <meta name="author" content="Sam Verschueren">

    <script type="text/javascript" src="content/scripts/jquery-1.8.0.min.js"></script>
    
    <link href="content/site.css" rel="stylesheet" type="text/css" />
</head>

<body>

<div id="page">
    <header>
        <div class="center">
            <h1>.P MVC framework</h1>
            
            <h2>This is an example page of the .P mvc framework.</h2>
            
            <nav>
                <ul>
                    <li><a href="Home">Home</a></li>
                    <li><a href="Home/About">About</a></li>
                    <li><a href="Home/Contact">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>
    
    <div id="main" class="center">
        <?php
            if(isset($viewData['error'])) {
                echo '<div id="error">' . $viewData['error'] . '</div>';
            }
        ?>
            
        <?php renderBody(); ?>
    </div>
    
    <footer>
        <p class="center">
            <span class="floatLeft">2012</span>
            
            <span class="floatRight">Created by Sam Verschueren</span>
        </p>
    </footer>
</div>

</body>
</html>