<h1>About</h1>

<p>
    This project was originally created for the website histranger. But it's purpose is going further then that. It can be used to create
    MVC websites in PHP and is based on the MVC .NET framework.
</p>

<p>
    The three parts of an MVC application are fully separated. This makes it easier for the developer to rapidly create complex websites.
</p>

<p>
    You can use a database to support your website. Unfortanetly, the framework does not help you with this yet. This will be supported in future
    versions of the framework.
</p>